### ISSUE TITLE
Console ID problem

### ISSUE THREAD

**Issue by Jhynjhiruu** [Jimmy-Z/fwTool#2]
TWLnf tells me my Console ID is incorrect, when I'm 100% sure it's correct. Maybe include an example Console ID file?

**Comment by Jimmy-Z** [comment]
Follow up here if anyone is interested:
http://gbatemp.net/threads/wip-twlnf-dsi-nand-file-thing-testers-with-hardmod-wanted.484690/page-3#post-7620530
